// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0UUFSti9NrWzRLAzov_5SZtOwpf7SaM',
    appId: '1:1047931177971:web:8640e6a146d74d0dc86086',
    messagingSenderId: '1047931177971',
    projectId: 'food-delivery-flutter-1212',
    authDomain: 'food-delivery-flutter-1212.firebaseapp.com',
    storageBucket: 'food-delivery-flutter-1212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA367t0uqR3bIf9YtoPNZIHONd_jzDdliA',
    appId: '1:1047931177971:android:dcea2499d053b176c86086',
    messagingSenderId: '1047931177971',
    projectId: 'food-delivery-flutter-1212',
    storageBucket: 'food-delivery-flutter-1212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHJbe1joESFH3crzZelhqno7WHehmkqo',
    appId: '1:1047931177971:ios:18f1aada00abb03dc86086',
    messagingSenderId: '1047931177971',
    projectId: 'food-delivery-flutter-1212',
    storageBucket: 'food-delivery-flutter-1212.appspot.com',
    iosClientId: '1047931177971-34sbpsjvqhhg43eqhlat2r2hkbrdo3uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryAppFlutter',
  );
}
